### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by dan-leo** [tutts/google-sites-markdown#3]
I pasted the code as stated in the readme, and then nothing happens?

**Comment by tutts** [comment]
Hi @dan-leo, I've just tested on a fresh site, and it still works, Google now even displays it in the preview which is great. Do you have steps to reproduce or any errors at all?

![image](https://user-images.githubusercontent.com/7454558/93450548-03dd2f00-f8ce-11ea-8a14-2ef490eb8b16.png)

![image](https://user-images.githubusercontent.com/7454558/93450598-0f305a80-f8ce-11ea-97b9-3e4b4750f18c.png)

![image](https://user-images.githubusercontent.com/7454558/93450632-18b9c280-f8ce-11ea-9035-48d806b0bf27.png)

**Comment by dan-leo** [comment]
Oh my word, it was grammarly! HAhah! Happiness.

**Comment by ekorudiawan** [comment]
It doesn't work for me, @dan-leo how do you solve your problem?
